name: Discourse Plugin

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    # Replaces discourse/.github/.github/workflows/discourse-plugin.yml@v1
    uses: qiime2-cutlery/discourse-dotgithub/.github/workflows/discourse-plugin.yml@main
